# Generated by Django 4.0 on 2021-12-31 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='All_File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('File_link', models.TextField(blank=True, default='00000', null=True)),
                ('FileName', models.TextField(blank=True, default='000000', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Feature_image', models.FileField(upload_to='static/alax')),
            ],
        ),
        migrations.CreateModel(
            name='FirebaseStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apiKey', models.TextField(blank=True, default='dsfc', null=True)),
                ('authDomain', models.TextField(blank=True, default='dsfc', null=True)),
                ('databaseURL', models.TextField(blank=True, default='dsfc', null=True)),
                ('storageBucket', models.TextField(blank=True, default='dsfc', null=True)),
            ],
        ),
    ]
